/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Gio.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Gio.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[1.067, 6.6, 0.596]} rotation={[Math.PI / 2, 0, 0]} scale={56.128}>
        <mesh geometry={nodes.Curve001.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Curve001_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Curve001_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Curve001_3.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Curve001_4.geometry} material={materials['SVGMat.001']} />
        <mesh geometry={nodes.Curve001_5.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Curve001_6.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Curve001_7.geometry} material={materials.Material} />
        <mesh geometry={nodes.Curve001_8.geometry} material={materials['Material.009']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Gio.gltf')
