/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Gio.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Gio.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.529, 1.887, 0.136]} rotation={[Math.PI / 2, 0, 0]} scale={[0.728, 0.458, 1.855]}>
        <mesh geometry={nodes.Circle_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Circle_2.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Circle_3.geometry} material={materials.Material} />
      </group>
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.009']} position={[0.839, 3.435, -0.13]} rotation={[-Math.PI / 2, 0, 0]} scale={0.024} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.009']} position={[0.218, 3.435, -0.13]} rotation={[-Math.PI / 2, -0.641, 0]} scale={0.024} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.009']} position={[0.541, 3.649, -0.13]} rotation={[-Math.PI / 2, 0.751, 0]} scale={0.024} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.009']} position={[1.022, 0.25, -0.13]} rotation={[-Math.PI / 2, 0, 0]} scale={0.024} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials['Material.009']} position={[0.085, 0.25, -0.13]} rotation={[-Math.PI / 2, -0.641, 0]} scale={0.024} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['Material.009']} position={[0.541, 0.083, -0.13]} rotation={[-Math.PI / 2, 0.751, 0]} scale={0.024} />
      <group position={[-0.854, 0.848, 0.007]} scale={[0.232, 0.811, 0.232]}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Curve004.geometry} material={materials['SVGMat.001']} position={[-1.019, 1.668, 0.165]} scale={4.037} />
      <mesh geometry={nodes.Curve.geometry} material={materials['SVGMat.001']} position={[-0.713, 7.088, 0.679]} scale={17.388} />
      <mesh geometry={nodes.Curve001.geometry} material={materials['SVGMat.001']} position={[-0.7, 7.647, 0.679]} scale={17.388} />
      <mesh geometry={nodes.Curve002.geometry} material={materials['SVGMat.001']} position={[-0.713, 8.024, 0.679]} scale={17.388} />
      <mesh geometry={nodes.Curve003.geometry} material={materials['SVGMat.001']} position={[-0.704, 7.119, 0.679]} scale={17.388} />
      <mesh geometry={nodes.Curve005.geometry} material={materials['Material.004']} position={[0.016, 1.556, 0.146]} rotation={[Math.PI / 2, 0, 0]} scale={13.031} />
      <mesh geometry={nodes.Curve006.geometry} material={materials['Material.005']} position={[0.523, 2.684, 0.014]} rotation={[-Math.PI / 2, 0, 0]} scale={[-148.262, -21.942, -137.885]} />
    </group>
  )
}

useGLTF.preload('/Gio.gltf')
